# Generated by Django 5.1.5 on 2025-01-29 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0002_remove_subject_description_remove_subject_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathVideoTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyapp.subject')),
            ],
        ),
    ]
