# Generated by Django 5.1.5 on 2025-01-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0003_mathvideotutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='study_notes/')),
                ('subject_name', models.CharField(max_length=255)),
            ],
        ),
    ]
