# Generated by Django 5.1.5 on 2025-01-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0006_csstudynote_malstudynote_csvideotutorial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('eng', 'English'), ('cs', 'Computer Science'), ('math', 'Mathematics'), ('mal', 'Malayalam')], max_length=10)),
                ('file', models.FileField(upload_to='question_papers/')),
                ('year', models.CharField(max_length=4)),
            ],
        ),
    ]
